# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6fb0fda58c6db8c253f86ca088889442"
name = "POS-app"
handle = "pos-app-65"
application_url = "https://pos-app-azure.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://pos-app-azure.vercel.app/auth/callback", "https://pos-app-azure.vercel.app/auth/shopify/callback", "https://pos-app-azure.vercel.app/api/auth/callback"]

[pos]
embedded = false
